USE master
GO
CREATE DATABASE RH_TRANSACT
ON
( NAME =RH_TRANSACT_DAT, 
FILENAME = 'c:\RH_TRANSACT\RH_TRANSACT.mdf',
size = 15, MAXSIZE = 50, FILEGROWTH = 5 )
LOG ON
( NAME = RH_TRANSACT_LOG,
FILENAME = 'c:\RH_TRANSACT\RH_TRANSACT.ldf',
SIZE = 5MB, MAXSIZE = 25MB, FILEGROWTH = 5MB )
GO